### ISSUE TITLE
No such file or directory after vibrant

### ISSUE THREAD

**Issue by XC-Zhai** [uio-bmi/VirMake#9]
Thanks for this pipeline. I tried to run 2 samples and had the following issue with **Error in rule checkv_vibrant:**

diamond v2.0.4.142 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 40
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /VirMake/databases/checkv/checkv-db-v1.5/genome_db/checkv_reps.faa
Opening the database file...  [0.205s]
Loading sequences...  [4.916s]
Masking sequences...  [9.364s]
Writing sequences...  [1.159s]
Hashing sequences...  [0.485s]
Loading sequences...  [0s]
Writing trailer...  [0.08s]
Closing the input file...  [0.01s]
Closing the database file...  [2.182s]
Database hash = 717e6a7635cc537b719f2a2c9eea33e8
Processed 3736378 sequences, 820392034 letters.
Total time = 18.405s
Traceback (most recent call last):
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/bin/checkv", line 10, in <module>
    sys.exit(cli())
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/lib/python3.10/site-packages/checkv/cli.py", line 117, in cli
    args["func"](args)
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/lib/python3.10/site-packages/checkv/modules/end_to_end.py", line 59, in main
    checkv.contamination.main(args)
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/lib/python3.10/site-packages/checkv/modules/contamination.py", line 337, in main
    utility.check_fasta(args["input"], args["tmp"])
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/lib/python3.10/site-packages/checkv/utility.py", line 92, in check_fasta
    f = get_compressed_file_handle(path)
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/lib/python3.10/site-packages/checkv/utility.py", line 55, in get_compressed_file_handle
    filepath_compression = is_compressed(path)
  File "/VirMake/working_dir/.snakemake/conda/90f5c2c615a1b66ffbb59601b584571b_/lib/python3.10/site-packages/checkv/utility.py", line 42, in is_compressed
    with open(filepath, "rb") as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'VirMake/working_dir/output/vibrant_pass1/NXT078_NXT078_ZXC348_S105/VIBRANT_contigs/VIBRANT_phages_contigs/contigs.phages_combined.fna'

However, I noticed the contigs.phages_combined.fna just under folder 'VirMake/working_dir/output/vibrant_pass1/NXT078_NXT078_ZXC348_S105/' and both VIBRANT_contigs and VIBRANT_phages_contigs are empty and also under folder 'VirMake/working_dir/output/vibrant_pass1/NXT078_NXT078_ZXC348_S105/'

Any help to figure it out?
Thanks in advanced.

**Comment by XC-Zhai** [comment]
rerun it and works again now.
